### ISSUE TITLE
Preview SDK Enhancements/Help Wanted

### ISSUE THREAD

**Issue by ezestkuldeep** [box/box-ios-preview-sdk#2]
How to use preview SDK for offline files after getting downloaded. right now it only allows to show files from Box SDK.

**Comment by h2kuo** [comment]
Hi @ezestkuldeep, can you clarify what you mean by offline files vs. files from the Box SDK? 

You should be able to view your files on Box offline by using a combination of BOXPreviewClient's ```cacheFileWithID:progress:completion:``` to download a specific file while online, and then implementing BOXPrereviewClientDelegate's method ```shouldPreviewClient:deleteCacheForFileWithID:``` to return NO for files you want to persist in the cache for offline use. 

Please let us know if that helps, or if you need further assistance.

**Comment by ezestkuldeep** [comment]
The idea here is I want the files to be available and shown even if the network connection is off.  As it happens in Box App when you mark a file as "save for offline". 
Can you help me identify how to present or show a file from Box offline.  At present the preview controller needs a BoxItem object to be passed to show a file how the cache will return me that object is the loose string Im not able to connect.
Also the in the above API what is the FileID is this the sequenceID from BoxItem ?

**Comment by h2kuo** [comment]
The FileID will be the modelID from BOXModel (which BOXItem extends from).

The interfaces aren't exactly optimal for this situation (and we will try to improve them in the future), but for now you should be able to do the following:
You can get a BOXFile object through the completion block for ```cacheFileWithID:progress:completion:```
e.g.
```objc
[self cacheFileWithID:fileID progress:nil completion:^(BOXFile *file, NSError *error) {
   if (error == nil) {
      // store BOXFile
   }
}];
```
This will return the file that has been cached, and you can later use to present in the controller. You can also use the BOXFile objects returned from Content SDK requests like fileInfoRequest, as long as ```cacheFileWithID:progress:completion:``` has been called for that file ID, since that is what actually downloads the file's preview. 

To help with storing the BOXFile objects, you can also use the JSONData property to retrieve a dictionary (to use with NSKeyedArchiver for example) and then later recreate the BOXFile like so:
```objc
NSDictionary *JSONData = originalBoxFile.JSONData;
BOXFile *newBoxFile = [BOXFile initWithJSON:JSONData];
```
You can pass this recreated BOXFile to the file preview controller. 

Hopefully this works for you! Let us know if you have additional questions.

**Comment by ezestkuldeep** [comment]
Thank you !! This documentation helped me a lot to implement my use case.
