### ISSUE TITLE
Sample App Documentation Enhancement

### ISSUE THREAD

**Issue by austinringer** [box/box-ios-preview-sdk#4]
Hi All, 

I work on the Demo Engineering team at Box and recently pulled box-ios-preview-sdk to check it out and work on a project. Love it!

I did notice a minor documentation-related point that may help beginner iOS developers like myself get going. 

When I followed steps to run the BoxPreviewSDKSampleApp that the `#import <BoxPreviewSDK/BoxPreviewSDK.h>` statement caused an error. It may be worth noting that the BoxPreviewSDK.h lives in Pods directory and that the path is slightly different. Finding the file and adding the absolute path totally resolved the issue. 

I'm a big fan of your teams work and I look forward to exploring these sdk's more deeply. 

Big thanks.
Austin

**Comment by h2kuo** [comment]
Hi @austinringer, thanks for the feedback! I just noticed this as well, and this is most likely related to an inconsistency with the setup of the framework. If you try ```#import <BoxPreviewSDK.h>``` is it able to correctly find the file? What is the current import statement you are using?

We will be working on fixing this so that we can keep the importing process consistent with our other SDKs.

**Comment by austinringer** [comment]
@h2kuo Thanks for getting back to me on this. I'm just using the full absolute path to the BoxPreviewSDK.h file in the Pods directory. Using `#import <BoxPreviewSDK.h>` doesn't seem to work for me.

**Comment by h2kuo** [comment]
@austinringer, we recently updated our Cocoapod to v1.0.1. Could you please try updating and using the ```#import <BoxPreviewSDK/BoxPreviewSDK.h>``` statement and let us know if it works now? Thanks!

**Comment by h2kuo** [comment]
@austinringer Feel free to reopen this issue if you're still running into errors.
