### ISSUE TITLE
BoxPreviewSDK fails to load the image -get an error "Unable to load image" when a new BoxContentClient Instance not passed

### ISSUE THREAD

**Issue by ManasaMS85** [box/box-ios-preview-sdk#56]
### Description of the Issue

Box Preview SDK fails to load the image with a shared instance session passed from box-content client after instantiating the new client in for boxcontent client. even when box content client is logged out and the boxcontent client instance as well cleared initially.

We would like to use a single shared instance of boxcontentclient across the app for one user for both BoxContentclient and BoxPreviewClient - Instantiating multiple boxcontentclient will add to latency as we would be again fetching an access token - which is a web service call in our app.

### Versions Used
Preview SDK: Box Preview SDK - 2.2.0
iOS: iOS 11 and iOS 12

### Steps to Reproduce
Sample app shared "Allstate.boxtest_filePreviewfails" - Where the box preview fails - using the BoxContentclient Shared instance 
1. Change the auth token in "BoxService" .
2. Run the app - on first launch -Tap on go to Preview
3. Unable to load image error is shown

Sample app shared for passing case "Allstate.boxtest_filePreviewPasses" - Where the box preview fails - Initializing the Box Content Client again
1. Change the auth token in "BoxService" .
2. Run the app - on first launch -Tap on go to Preview
3. Image is loaded

### Error Message, Including Stack Trace
We get an error "Unable to load image" for image and "Not enough space"  for a file, when a new BoxContentClient Instance not passed
Sample app shared to reproduce

**Comment by mattwiller** [comment]
@ManasaMS85 Looking over the failing sample app, I can spot two immediate issues:

1. In your `BoxService#logout()` function, you call `.logOut()` on one client and then instantiate a new client with the `uniqueId` of the `ServerAuthUser` set to `nil`.  The `uniqueId` __MUST__ have a string value, otherwise you'll run into issues with the Preview SDK.  On my machine, I put a dummy value instead of `nil`, and the issue you described went away.  Can you check on your end to see if that works for you?

2. You have a call to `autheticateAppUser()` in your login logic; this should be removed in favor of creating a new client whenever you are switching users.  I think this code might just be left over from something else, but wanted to make sure to call out that this method should not be used.

Fundamentally, a client represents a single user session.  The `uniqueId` you enter when creating the client is used in the Preview SDK, and it must be unique to each user.  You need to have a different client for each active user, and cannot re-use the same client if you're authenticating as two different users.  If you intend to switch users often and want to avoid needing to call the server again and again for new tokens, you could potentially keep a reference to each user's client (and not log them out).

**Comment by ManasaMS85** [comment]
@mattwiller - The first resolution - resolved my issue - we had set the user to nil to clear the instance of old Box Client - Now made it a "" and things worked fine. 
Wouldn't it be nice if you make the Unique ID as mandatory. 

The Second part of code is a left over code which we were trying for some other thing.
